### ISSUE TITLE
Calculating the distance

### ISSUE THREAD

**Issue by zaher88abd** [LearnTechWithUs/Stereo-Vision#5]
Hi,

May I ask you to explain this line of the code, for which reason you are using those numbers.
`
Distance= -593.97*average**(3) + 1506.8*average**(2) - 1373.1*average + 522.06
`

Thanks.

**Comment by UndecidedBoy** [comment]
Hello,

This equation converts the values from the disparity map to a distance.
We use here a polynomial equation of order 3 as explained in your PDF since it represents the best fit for converting disparity in stereo to distance. How we established the coefficients is described somewhere in the youtube comments or also in the discussion part of the youtube channel.

Hope this helps.

Have a nice day/evening!
